version: '3.2'

services:
  server:
    build:
      context: ./chatgpt_server
      dockerfile: Dockerfile
    restart: always
    environment:
      - CHATGPT_CHECK_PERIOD=86400 # 限频监测时间
      - CHATGPT_MAX_TIMES=50 # 单次会话最大提问数
      - OPENAI_KEY=必填 # openAI的key
    networks:
      - chatgpt

  web:
    build:
      context: ./chatgpt_web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 18080:80
    networks:
      - chatgpt
    depends_on:
      - server
    
networks:
    chatgpt:
      external: false